# File              : configure.yml
# Author            : Rustam Khafizov <super.rustamm@gmail.com>
# Date              : 25.09.2020
# Last Modified Date: 26.09.2020
# Last Modified By  : Rustam Khafizov <super.rustamm@gmail.com>

---
- name: putting flannel network config into etcd3 storage
  become: true
  etcd3:
    key: "{{ etcd_prefix | default('/coreos.com/network') }}/config"
    value: |
      {{ network_config }}
    state: present
    host: "{{ etcd_endpoints | raw_ip() }}"
    port: "{{ etcd_endpoints | raw_ip('port') }}"
    ca_cert: "{{ etcd_cafile }}"
    client_cert: "{{ etcd_certfile }}"
    client_key: "{{ etcd_keyfile }}"
  when: etcd_config

- name: installing flannel service
  become: true
  template:
    src: flannel.service
    dest: "/etc/systemd/system"
    mode: 0644
    owner: root
  notify:
    - enable flannel
