# File              : install.yml
# Author            : Rustam Khafizov <super.rustamm@gmail.com>
# Date              : 16.09.2020
# Last Modified Date: 03.10.2020
# Last Modified By  : Rustam Khafizov <super.rustamm@gmail.com>

---
- name: updating before installing
  become: true
  apt:
    update_cache: true
    cache_valid_time: 0
    force_apt_get: true
    upgrade: dist

- name: downloading flannel binaries
  become: true
  get_url:
    url: "https://github.com/coreos/flannel/releases/download/v{{ version }}/flannel-v{{ version }}-linux-amd64.tar.gz"
    dest: "/tmp/flannel.tar.gz"
    mode: 0644
    owner: root

- name: unpacking flannel binaries
  become: true
  unarchive:
    src: "/tmp/flannel.tar.gz"
    dest: "/tmp"
    remote_src: true

- name: installing python etcd3
  become: true
  pip:
    name: etcd3
  when: network_config_file

- name: installing flannel binaries
  become: true
  copy:
    src: "/tmp/flanneld"
    dest: "/usr/bin"
    owner: root
    mode: 0755
    remote_src: true
