# File              : main.yml
# Author            : Rustam Khafizov <super.rustamm@gmail.com>
# Date              : 25.09.2020
# Last Modified Date: 25.09.2020
# Last Modified By  : Rustam Khafizov <super.rustamm@gmail.com>

---
- name: enable flannel
  become: true
  systemd:
    name: flannel
    state: started
    enabled: true
    daemon_reload: true
